services:
  - type: web
    name: hottof-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7413532622:AAHCSzCHmbgtMwn5wqJ5S1wCPxSW8ReSTpk
      - key: ADMIN_IDS
        value: 6387942633
      - key: CHANNEL_ID
        value: @hottof
      - key: WEBHOOK_URL
        value: https://final-4oxs.onrender.com.onrender.com/webhook
